[build-system]
requires = ["hatchling>=1.0.0"]
build-backend = "hatchling.build"

[project]
name = "ascribe_link"
version = "0.1.0"
description = ""

[tool.hatch.metadata]
packages = ["ascribe_link"]

dependencies = [
    "numpy>=1.20",
    "pyvista>=0.34",
    "paho-mqtt>=1.6",
]

dev-dependencies = [
    "pytest>=6.2",
]
